### ISSUE TITLE
Error: overflow (fault="overflow", operation="toNumber")

### ISSUE THREAD

**Issue by chekun** [CryptoManiacsZone/1inchProtocol#38]
Hi guys, I follow the readme guide, but stuck with this error when calling `getExpectedReturnWithGas`, for `destTokenEthPriceTimesGasPrice` arg, it always return error with something like 

```
Error: overflow (fault="overflow", operation="toNumber", value="925003271924762633938248194741364019606826595687598837055279805260905", code=NUMERIC_FAULT, version=bignumber/5.0.5)
```

Guide says arg `destTokenEthPriceTimesGasPrice`  is ` returnAmount * gas_price, where returnAmount is result of getExpectedReturn(fromToken, destToken, amount, parts, flags)`, how do i get into this error? Please help me , Thank you very much.

Example code:

```js
const { returnAmount, distribution } = await contract.methods.getExpectedReturn(
  '0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE',
  daiAddress,
  web3.utils.toWei('100', 'ether'),
  parts,
  0x00,
).call();
console.log('expected return -> ', returnAmount);
const destTokenEthPriceTimesGasPrice = web3.utils.toBN(returnAmount).mul(web3.utils.toBN(200*Math.pow(10, 9)));

const { returnAmount: a, estimateGasAmount,  distribution: b} = await contract.methods.getExpectedReturnWithGas(
  '0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE',
  daiAddress,
  web3.utils.toWei('100', 'ether'),
  parts,
  0x00,
  destTokenEthPriceTimesGasPrice,
).call();
console.log(a);
```

PS: i'm using `web3@1.2.1`

**Comment by cryptopixelfrog** [comment]
@chekun what was your solution for this? I am having same issue with you.

**Comment by m0onspell** [comment]
hey, how did you solve it? can you please share?

**Comment by chekun** [comment]
@m0onspell 
could not recall how i resole it, maybe try to approve ahead?
