### ISSUE TITLE
getExpectedReturnWithGas and swapWithReferral is not available in contract address

### ISSUE THREAD

**Issue by Resoguy** [CryptoManiacsZone/1inchProtocol#47]
Hi, I am trying to use `getExpectedReturnWithGas` and `swapWithReferral` methods from the contract address in the documentation which is `0xC586BeF4a0992C495Cf22e1aeEE4E446CECDee0E`. And I get error calling these methods.

And when I checked the address's source code I couldn't see these methods. So what happened to these methods?

Thanks

**Comment by AndyTCF** [comment]
How are you calling these methods? i.e via ABI?

**Comment by Resoguy** [comment]
Yes I am using abi that I took from contract address's etherscan url and also tried with the abi from docs but it just cant find methods and get this error:

`Uncaught (in promise) Error: call revert exception (address="0xC586BeF4a0992C495Cf22e1aeEE4E446CECDee0E", args=["0x2C537E5624e4af88A7ae4060C022609376C8D0EB","0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE","1500000000",10,0,0], method="getExpectedReturnWithGas(address,address,uint256,uint256,uint256,uint256)", errorSignature="Error(string)", errorArgs=[["OneSplit: do not send ETH directly"]], reason=["OneSplit: do not send ETH directly"], transaction={"to":{},"data":"0x8373f2650000000000000000000000002c537e5624e4af88a7ae4060c022609376c8d0eb000000000000000000000000eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee0000000000000000000000000000000000000000000000000000000059682f00000000000000000000000000000000000000000000000000000000000000000a00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"}, version=4.0.47)
`

**Comment by Resoguy** [comment]
The contract address in the docs does not include all the methods in the docs so the correct address if you want to use all methods in the docs you should use this contract address: `0x50FDA034C0Ce7a8f7EFDAebDA7Aa7cA21CC1267e`
